### ISSUE TITLE
When updating, foundry looks for incorrect manifest url

### ISSUE THREAD

**Issue by Metacomet10** [MannyKSoSo/Manny-Language#1]
There was a commit (`17184245e8f2fc95e1ec5dcec383eb40c7b84bea`) that fixed the incorrect url. However, that commit has not been put into a release, so Foundry is still trying to download 1.0.1 from the Releases section, which has the old url. When attempting to update after installing directly from the [manifest](https://raw.githubusercontent.com/MannyKSoSo/Manny-Language/main/module.json), it's giving the following error.
<img width="800" alt="Screen Shot 2020-11-26 at 6 53 34 PM" src="https://user-images.githubusercontent.com/6789837/100405627-d7096e80-3018-11eb-914f-f5d92fb836cf.png">

**Comment by MannyKSoSo** [comment]
I have created the release 1.0.3 (1.0.2 decided not to wanna play nice so had to skip that version) so the newest version has been pushed.

I also apologies that this took me a bit as I was away from home and did not have a computer to update this.
